sch_wl:
    resource: "@SchWlBundle/Controller/"
    type:     annotation
    prefix:   /
login:
    pattern:   /login
    defaults:  { _controller: SchWlBundle:Security:login }
login_check:
    pattern:   /login_check

